[common]
# ==> NOTE: Replace with google spreadsheet id of stat file url
# Example: https://docs.google.com/spreadsheets/d/1pV-L2fj8nOwhK1XHNsPSqvC4OsV9HAUEyQA4Cr3U_0s/edit#gid=587257807
# (Get the part after /d/ but before /edit)
spreadsheetId = "1PVGB91CD-82Lhv2bNah6NrujkxbgWiCutN0SK7gBl3E"
# ==> NOTE: Replace with current month
month = 5
# Name of Column contains structure name
structureNameCol = "A"
# Name of Column contains leader name of structure
leaderNameCol = "B"
# Name of summary sheet
summarySheetName = "สรุป"
# List of range of column name that contains data in each week 
weekRange = ["C:M", "O:Y", "AA:AK", "AM:AW", "AY:BI"]
# List of data name in range (order from left to right)
metricColList = ["CH", "S", "BT", "ATP", "C", "On", "PC", "ผจ.", "ผส.", "ผก.", "Care"]
# Name of sheet to get followUp count for each week
followUpSheetNameList = ["Data_Wk1", "Data_Wk2", "Data_Wk3", "Data_Wk4", "Data_Wk5"]
# List of column name that contains data in each row 
followUpDataColumnList = ["X", "AO", "BC", "BQ", "CD", "CP", "DB", "DN", "DZ", "EL"]
# column name that contains data for leader follow up
leaderFollowUpDataColumn = "X"

# Metric of data and how to compute them
# Exclude 1:1 and Target since they have specific method to obtain the data
[metrics]
SBAC = "S + BT + ATP + C"
SBACON = "S + BT + ATP + C + On"
Care = "Care"
"ผจ." = "ผจ."
"ผส." = "ผส."

# ==> NOTE: Replace with this month target for each structure

[structure.UN1]
type = "RP"
target = 200
summaryRow = 8
followUpRow = 43

[structure.RinOne]
type = "SDL"
target = 45
summaryRow = 4
followUpRow = 9
dependencies = ["Eternal_Love"]

[structure.Eternal_Love]
type = "UL"
target = 44
summaryRow = 16
dependencies = ["DBU", "Balance", "Superior", "Promise"]

[structure.DBU]
type = "CL"
target = 10
summaryRow = 12
followUpRow = 4

[structure.Balance]
type = "CL"
target = 10
summaryRow = 13
followUpRow = 5

[structure.Superior]
type = "CL"
target = 11
summaryRow = 14
followUpRow = 6

[structure.Promise]
type = "CL"
target = 12
summaryRow = 15
followUpRow = 7

###################

[structure.Spirit]
type = "SDL"
target = 44
summaryRow = 5
followUpRow = 19
dependencies = ["KT", "Shalom"]

[structure.KT]
type = "UL"
target = 23
summaryRow = 27
dependencies = ["Shema", "Harmony", "Testimony"]

[structure.Shema]
type = "CL"
target = 9
summaryRow = 24
followUpRow = 13

[structure.Harmony]
type = "CL"
target = 7
summaryRow = 25
followUpRow = 14

[structure.Testimony]
type = "CL"
target = 7
summaryRow = 26
followUpRow = 15

[structure.Shalom]
type = "UL"
target = 20
summaryRow = 30
dependencies = ["Seniority", "Gabriella"]

[structure.Seniority]
type = "CL"
target = 9
summaryRow = 28
followUpRow = 16

[structure.Gabriella]
type = "CL"
target = 10
summaryRow = 29
followUpRow = 17

###################

[structure.KL]
type = "SDL"
target = 45
summaryRow = 6
followUpRow = 28
dependencies = ["Honest", "KLT"]

[structure.Honest]
type = "UL"
target = 15
summaryRow = 39
dependencies = ["Young_lnw"]

[structure.Young_lnw]
type = "CL"
target = 14
summaryRow = 38
followUpRow = 23

[structure.KLT]
type = "UL"
target = 29
summaryRow = 43
dependencies = ["Faithful", "Obey", "Excellent"]

[structure.Faithful]
type = "CL"
target = 8
summaryRow = 40
followUpRow = 24

[structure.Obey]
type = "CL"
target = 7
summaryRow = 41
followUpRow = 25

[structure.Excellent]
type = "CL"
target = 13
summaryRow = 42
followUpRow = 26

###################

[structure.KN]
type = "SDL"
target = 64
summaryRow = 7
followUpRow = 39
dependencies = ["Mighty", "Navigator"]

[structure.Mighty]
type = "UL"
target = 33
summaryRow = 54
dependencies = ["Godfrey", "Amity", "Galaxy"]

[structure.Godfrey]
type = "CL"
target = 12
summaryRow = 51
followUpRow = 32

[structure.Amity]
type = "CL"
target = 9
summaryRow = 52
followUpRow = 33

[structure.Galaxy]
type = "CL"
target = 12
summaryRow = 53
followUpRow = 34

[structure.Navigator]
type = "UL"
target = 30
summaryRow = 58
dependencies = ["Natia", "Esther", "Joshua"]

[structure.Natia]
type = "CL"
target = 9
summaryRow = 55
followUpRow = 35

[structure.Esther]
type = "CL"
target = 8
summaryRow = 56
followUpRow = 36

[structure.Joshua]
type = "CL"
target = 12
summaryRow = 57
followUpRow = 37





# [target]
# RinOne = 1
# Spirit = 1
# KL = 1
# KN = 1
# BSRU = 1
# Balance = 1
# Superior = 1
# Promise = 1
# Eternal_Love = 1
# Shalom = 1
# Shema = 1
# Harmony = 1
# KT = 1
# Young_lnw = 1
# Obey = 1
# Excellent = 1
# Honest = 1
# Mighty = 1
# Fairly = 1
# Skill = 1
# Nirvana = 1
# Niceness = 1
# New_Life_Full = 1
# Joshua = 1
# Navigator = 1

# # Row of the data of a structure in summary sheet
# [structure_data_row]
# RinOne = 4          # SDL
# Spirit = 5          # SDL
# KL = 6              # SDL
# KN = 7              # SDL
# BSRU = 12           # CL
# Balance = 13        # CL
# Superior = 14       # CL
# Promise = 15        # CL
# Eternal_Love = 16   # UL
# Shalom = 24         # CL
# Shema = 25          # CL
# Harmony = 26        # CL
# KT = 27             # UL
# Young_lnw = 35      # CL
# Obey = 36           # CL
# Excellent = 37      # CL
# Honest = 38         # UL
# Mighty = 46         # CL
# Fairly = 47         # CL
# Skill = 48          # UL
# Nirvana = 49        # CL
# Niceness = 50       # CL
# New_Life_Full = 51  # CL
# Joshua = 52         # CL
# Navigator = 53      # UL








# BSRU = 4           # CL
# Balance = 5        # CL
# Superior = 6       # CL
# Promise = 7        # CL
# Eternal_Love =    # UL
# RinOne =           # SDL

# Shalom = 13         # CL
# Shema = 14          # CL
# Harmony = 15        # CL
# KT =              # UL
# Spirit =           # SDL

# Young_lnw = 21      # CL
# Obey = 22           # CL
# Excellent = 23      # CL
# Honest =          # UL
# KL =               # SDL

# Mighty = 29         # CL
# Fairly = 30         # CL
# Skill =           # UL
# Nirvana = 31        # CL
# Niceness = 32       # CL
# New_Life_Full = 33  # CL
# Joshua = 34         # CL
# Navigator =       # UL
# KN =               # SDL

# UN1 = 40
